Repository msg-systems/ui5-testrecorder, pull requests merged in 2020-04, with the labels that each got.

#42 Replace 'markdown-styles' with 'showdown'
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: dependencies

#49 Stop recording when closing record dialog
  scripts/popup/controller/TestDetails.controller.js
Labels: bug

#52 Link fetching
  scripts/injected/pageInject.js
Labels: bug

#53 Minor fixes to controller and view 'Teststep'
  CHANGELOG.md
  scripts/popup/controller/TestStep.controller.js
  scripts/popup/css/additional.css
  scripts/popup/view/TestStep.view.xml
Labels: bug, documentation
